#!/bin/bash

# Sleeps to increment the system time by 1 second, leading to sequential
# random seeds
sleep 1; ./main runBeamOn.mac 
sleep 1; ./main runBeamOn.mac 
sleep 1; ./main runBeamOn.mac 
sleep 1; ./main runBeamOn.mac 
sleep 1; ./main runBeamOn.mac 
sleep 1; ./main runBeamOn.mac 
sleep 1; ./main runBeamOn.mac 
sleep 1; ./main runBeamOn.mac 
sleep 1; ./main runBeamOn.mac 
sleep 1; ./main runBeamOn.mac 
sleep 1; ./main runBeamOn.mac 
sleep 1; ./main runBeamOn.mac 
sleep 1; ./main runBeamOn.mac 
sleep 1; ./main runBeamOn.mac 
sleep 1; ./main runBeamOn.mac 
sleep 1; ./main runBeamOn.mac 
sleep 1; ./main runBeamOn.mac 
sleep 1; ./main runBeamOn.mac 
sleep 1; ./main runBeamOn.mac 
sleep 1; ./main runBeamOn.mac 

