# Set low energy EM processes, including fluorescence
/process/em/fluo true
/process/em/auger false
/process/em/augerCascade false
/process/em/pixe true
/process/em/deexcitationIgnoreCut false

/run/initialize

/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

# Set hit and signal file names
/dataCollection/setHitFileName hit_test25.csv
/dataCollection/setSignalFileName signal_test25.csv

/dataCollection/setPhotonFileName test25_photons.csv

# E0 of background distribution out of {100,200,300} keV
/particleSource/setFoldingEnergy 2.704 # [keV]

# 0 = background trapped electrons
# 1 = atmospheric backscattered electrons
# 2 = signal photons
# 3 = signal photons with various distributions
# 4 = signal photons from file
/particleSource/setBackgroundType 4

/run/beamOn 75000

