
/run/initialize
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/gps/source/clear

## Electron source
/gps/source/add 1

/gps/particle e-
/gps/pos/type Surface
/gps/pos/shape Sphere
/gps/pos/radius 15.0 cm
/gps/pos/centre 0. 0. 0. cm

# Energy distribution
/gps/ene/type Pow
/gps/ene/min 1 MeV
/gps/ene/max 100 MeV
/gps/ene/alpha -2

# Position distribution
/gps/ang/type cos
/gps/ang/mintheta 0. deg
/gps/ang/maxtheta 90. deg


# Run macro
/run/beamOn 100
